# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Setup keychain for ci"
  lane :setup do
    setup_project
  end
  
  private_lane :setup_project do
    create_keychain(
      name: "ci_keychain",
      password: "ci_keychain",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )
  end

  desc "Increment ios version"
  lane :increment_version do
    increment_build_number(xcodeproj: "DockApp.xcodeproj")
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(
      type: "appstore",
      readonly: true,
      keychain_name: "ci_keychain",
      keychain_password: "ci_keychain"
    )
    build_app(workspace: "DockApp.xcworkspace", scheme: "DockApp")
    upload_to_testflight
  end
end
