export const Routes = {
  SPLASH_SCREEN: 'splashScreen',
  CREATE_WALLET: 'createWallet',
  CREATE_WALLET_PROTECT: 'createWallet/protect',
  CREATE_WALLET_PASSCODE_SETUP: 'createWallet/passcode',
  CREATE_WALLET_PASSCODE: 'createWallet/passcodeSetup',
  UNLOCK_WALLET: 'unlockWallet',
  CREATE_ACCOUNT_BACKUP: 'createAccount/backup',
  CREATE_ACCOUNT_MNEMONIC: 'createAccount/mnemonic',
  CREATE_ACCOUNT_SETUP: 'createAccount/setup',
  CREATE_ACCOUNT_VERIFY_PHRASE: 'createAccount/',
  ACCOUNTS: 'accounts',
  ACCOUNT_DETAILS: 'account/details',
  ACCOUNT_IMPORT_FROM_MNEMONIC: 'account/importFromMnemonic',
  ACCOUNT_IMPORT_SETUP: 'account/importSetup',
  ACCOUNT_IMPORT_SETUP_PASSWORD: 'account/importSetupPassword',
  ACCOUNT_EXPORT_SETUP_PASSWORD: 'account/exportSetupPassword',
  APP_QR_SCANNER: 'app/qrScanner',
  APP_SETTINGS: 'app/settings',
  WALLET_EXPORT_BACKUP: 'wallet/exportBackup',
  WALLET_IMPORT_BACKUP: 'wallet/importBackup',
  WALLET_IMPORT_BACKUP_PASSWORD: 'wallet/importBackupPassword',
  
  // POC routes
  APP_HOME: 'app/home',
  APP_DID: 'app/did',
  APP_CREDENTIAL: 'app/credential',
  APP_CREDENTIAL_ISSUANCE: 'app/credentialIssuance',
  APP_PRESENTATION_EXCHANGE: 'app/presentationExchange',
  APP_SEND_TOKENS: 'app/appSendTokens',
  CREATE_WALLET_MNEMONIC: 'createWallet/mnemonic',
  BACKUP_CREATE: 'backup/create',
  BACKUP_LOAD: 'backup/load',
};
