export const Routes = {
  APP_HOME: 'app/home',
  APP_DID: 'app/did',
  APP_CREDENTIAL: 'app/credential',
  APP_CREDENTIAL_ISSUANCE: 'app/credentialIssuance',
  APP_PRESENTATION_EXCHANGE: 'app/presentationExchange',
  APP_QR_SCANNER: 'app/qrScanner',
  APP_SEND_TOKENS: 'app/appSendTokens',
  APP_SETTINGS: 'app/settings',
  CREATE_WALLET: 'createWallet',
  CREATE_WALLET_MNEMONIC: 'createWallet/mnemonic',
  UNLOCK_WALLET: 'unlockWallet',
  BACKUP_CREATE: 'backup/create',
  BACKUP_LOAD: 'backup/load',
};
