# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  
  
  desc "Submit a new Beta Build to Google Play"
  lane :internal do
    increment_version_code

    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    
    supply(
      track: 'internal',    
      apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH].to_s,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_changelogs: true,
    )
  end
end


